# Generated by Django 5.1.2 on 2024-10-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('repair_price', models.FloatField(default=0.0)),
                ('new_price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': ('Component',),
                'verbose_name_plural': ('Components',),
            },
        ),
    ]
