# Generated by Django 5.1.2 on 2024-10-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={},
        ),
    ]
