# Generated by Django 5.1.2 on 2024-10-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('issues', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
