# Generated by Django 5.1.2 on 2024-10-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_date_vehicle_final_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='component_type',
            field=models.CharField(max_length=20),
        ),
    ]
